set number
syntax on
set tabstop=4
call plug#begin()
Plug 'git@github.com:arcticicestudio/nord-vim.git'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()
